image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - deploy

deployToHeroku:
  type: deploy
  stage: deploy
  image: ruby:latest
  only:
    - master
    - staging
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY